### PR TITLE
Add an easy path for trusting the GeoTrust root certificate

### LINKED ISSUE #809: Consider adding default certificate for GeoTrust Global CA
We updated our Docker base image from OpenJDK 11 to OpenJDK 14 and our push notifications stopped working, root cause being _"sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"_.

I tested the same code on my Mac, also using OpenJDK 14, but everything worked correctly. Finally, I grabbed `/usr/local/openjdk-14/lib/security/cacerts` from the Docker image and started my test program using `-Djavax.net.ssl.trustStore=$HOME/tmp/cacerts-java14` and got the failure to reproduce locally.

I started to study the problem and found out that OpenJDK, along with browser vendors, has disabled support for GeoTrust Global CA, which is the root CA used by `api.push.apple.com`:

* https://blogs.oracle.com/java-platform-group/jdk-distrusting-symantec-tls-certificates
* https://groups.google.com/a/chromium.org/g/blink-dev/c/eUAKwjihhBs/m/El1mH8S6AwAJ?pli=1
* https://blog.mozilla.org/security/2018/03/12/distrust-symantec-tls-certificates/

However, the browser vendors seem to have [an exception](https://wiki.mozilla.org/CA/Additional_Trust_Changes#Symantec) for certificates signed by some known intermediary CAs (one being Apple's CA). I saw no evidence of such exception on JDK. Also, it seems that MacOS is configured to trust Apple's CA. Therefore, opening `api.push.apple.com` using a browser or default JDK settings on Mac works, but fails if JDK is instructed to only use `$JAVA_HOME/lib/security/cacerts`.

[Apple's APNS documentation](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html#//apple_ref/doc/uid/TP40008194-CH8-SW1) has a note that tells one to make sure that [GeoTrust_Global_CA.pem](https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Global_CA.pem) is trusted by the system. And sure enough: if we pass that to `ApnsClientBuilder.setTrustedServerCertificateChain`, everything works correctly.

This finally brings me to my issue: it's certainly possible to configure Pushy to work with Apple's APNS servers (I was so happy to find `setTrustedServerCertificateChain` which saved the day). And of course one could consider this to be an issue with JDK or the environment and not with Pushy.  But since OpenJDK on Docker without any extra certificates is probably a pretty common deployment target for Pushy, I think more and more people will bump into this same issue. So it would be really nice is Pushy would just work out-of-the-box. Or if messing with the default certificates feels bad, perhaps the situation could be detected and Pushy could give an informative error message with a link to the documentation?

### PR DESCRIPTION
**Pull request by jchambers**
This fixes #809 by including a copy of the GeoTrust root certificate with Pushy and providing an easy path for users to add it as a trusted certificate.

This pull request represents one of two potential approaches to addressing the issue. Feedback is very welcome. I've left a couple of documentation TODOs in the code, and will resolve those before merging.

----

TODO:

- [ ] Add concrete links to a page explaining The Deal™ with trusted certificates

### CODE REVIEW

**Comment by jmason** [comment]
This looks like a solid fix to me.  wow, TLS PKI is such a mess :(

**Comment by jchambers** [comment]
@jmason Thanks for weighing in (and it's good to hear from you)!

**Review by eager — APPROVED** [review]

**Comment by zsiegel** [comment]
Is there any update on this getting merged? I am running into this when deploying to GCP and it be great to have this. Let me know if there is anything I can do to help.

**Comment by jchambers** [comment]
Thanks—I appreciate the offer for help. The situation right now is that I'm really, really, really busy with my day job and just haven't been able to give this the attention it deserves. I'm hoping that will change shortly, though! I don't think there's anything to be done from the outside; I just need a clear enough runway to focus on Pushy for a contiguous stretch of time. I apologize for the delay in the meantime.

**Comment by zsiegel** [comment]
No worries! I can work around this manually given the API for adding a certificate is already there. Thank you for your response appreciate it.

**Comment by jchambers** [comment]
Folks, as mentioned in #809, I think the need for this has passed. I'm embarrassed to have taken so long to get this out, but don't think shipping it (or an updated version of it) would be helpful right now. Please let me know if you disagree, but I'll close this for now.

**Pull request closed without merging**
