### PR TITLE
json parser fix

### PR DESCRIPTION
**Pull request by kissmikki**
fix of issue: https://github.com/jchambers/pushy/issues/795

### CODE REVIEW

**Comment by kissmikki** [comment]
> Also, may I ask how this came to your attention? While I agree that this is a bug, I think the only things Pushy should be parsing in production are APNs error responses. Did you encounter this issue while using Pushy in normal operation, or were you trying to do something fancier?

We have a set of notification artifacts that handle a various client notifications such as sending push to iOS. I used Pushy to create a new artifact that fits into our existing framework and since I saw it has a json parser I used it. I extract a key from the string encoded payload (which is generated by Pushy's PayloadBuilder) and noticesdthat the decoded values were different from the encoded ones.

Sure, I can move the test - when I'm back from holiday.

**Comment by jchambers** [comment]
> Sure, I can move the test - when I'm back from holiday.

Don't sweat it. I'll just merge this and do a quick follow-up commit.

As soon as I can figure out why Travis isn't running tests, anyhow. Hm.

**Comment by jchambers** [comment]
Well, the tests definitely passed: https://travis-ci.org/github/jchambers/pushy/builds/708254193. It looks like the results just didn't make it back to github. I'll go ahead and merge this. Thank you for the contribution!

**Comment by jchambers** [comment]
> I'll just merge this and do a quick follow-up commit.

Done in 1639656a.

**Pull request merged**
